DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS `users` (
  `identifier` varchar(50) DEFAULT NULL,
  `permission_level` int(11) NOT NULL DEFAULT '0',
  `money` int(11) NOT NULL DEFAULT '0',
  `bank` int(11) NOT NULL DEFAULT '0',
  `group` varchar(30) CHARACTER SET utf8 NOT NULL DEFAULT 'user'
 ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- NO TOUCHY, IF SOMETHING IS WRONG CONTACT ANYONE BUT THE PERSON THAT SENT YOU THIS FILE! --
-- NO TOUCHY, IF SOMETHING IS WRONG CONTACT ANYONE BUT THE PERSON THAT SENT YOU THIS FILE! --
-- NO TOUCHY, IF SOMETHING IS WRONG CONTACT ANYONE BUT THE PERSON THAT SENT YOU THIS FILE! --
-- NO TOUCHY, IF SOMETHING IS WRONG CONTACT ANYONE BUT THE PERSON THAT SENT YOU THIS FILE! --essentialmode